### ISSUE TITLE
Add github actions to run ci

### ISSUE THREAD

**Issue by enieber** [terramagna/http-problem#2]
when I clone the project has some errors in tests. To help this not occur again my suggestion is add github action to run ci pipeline and verify the result of command: `cargo test`

**Comment by luisholanda** [comment]
Hi @enieber. Having errors in the tests sounds weird as our internal CI passes (maybe a configuration mismatch?); I'll take a look.

We must first merge PRs sent to this repo to our internal monorepo (to ensure we keep in sync with the OSS) version. This is why the repo doesn't have a CI. But it should be nice to have to make it easier to manage external contributions; I'll take a look at #3.
